#!/bin/bash
# RAYLEIGH COMPUTING SHORTCUTS
# non-parallel routines
echo "Executing /home1/lmatilsk/environment/bashrc_ra_routines"
#echo "ls -l ~/.bashrc"
#echo `ls -l ~/.bashrc`
echo "========================================================="

alias gi="python $raco/grid_info.py"
alias qi="python $raco/quantity_index.py"
alias tachref="python $raco/ideal_hydro_reference_state/generate_CZ_RZ_reference-quart.py"
alias ttrans="python $raco/print_translated_times.py"
alias simt="python $raco/simtime.py"
alias irate="python $raco/iter_rate.py"

# TIMEAVG routines # parallelized ------------------------ 
alias tav="$ppc $raco/timeavg/radata.py"
alias magtorque="$ppc $raco/timeavg/mag_torque.py"
alias indalt="$ppc $raco/timeavg/induct_alt.py"
alias indaltnum="$ppc $raco/timeavg/induct_alt_num.py"
alias vxb="$ppc $raco/timeavg/vcrossb.py"
alias bcor="$ppc $raco/timeavg/bcor.py"
alias meprod="$ppc $raco/timeavg/me_prod.py"
alias meprodshear="$ppc $raco/timeavg/me_prod_shear.py"
alias meprodmean="$ppc $raco/timeavg/me_prod_mean.py"
alias ferraro="$ppc $raco/timeavg/ferraro.py"

# helper (non-parallel) -------------------------------
alias tavjoin="python $raco/timeavg/timeavg_join.py"
alias ttrjoin="python $raco/timetrace/timetrace_join.py"

# TIMETRACE routines
# parallelized ------------------------
alias gtr="$ppc $raco/timetrace/G_Avgs.py"
alias gtr2="$ppc $raco/timetrace/G_Avgs_2dom.py"
alias gtrq="$ppc $raco/timetrace/G_Avgs_quad.py"
alias drc="$ppc $raco/timetrace/drc_2dom.py"
alias ty="$ppc $raco/timetrace/timey.py"
alias tlon="$ppc $raco/timetrace/timelon.py" 
# need to parallelize --------------------------------
alias ltr="python $raco/timetrace/lvals.py"

# PLOTTING routines (parallelized)
alias dramommc="$ppc $rapl/azav/dr_amom_mc_times_sample.py"
alias torquetimes="$ppc $rapl/azav/torque_times_sample.py"
alias molltimes="$ppc $rapl/sslice/moll_times_sample.py"

# RAYLEIGH PLOTTING SHORTCUTS (non-parallel)

# sim parameters
alias res="python $rapl/resolution.py"
alias ref="python $rapl/reference.py"
alias trans="python $rapl/transport.py"
alias eqconst="python $raco/eq_constants.py"
alias freq="python $raco/output_freq.py"

# AZ_Avgs routines
alias azav="python $rapl/azav/azav.py"

# mean flows
alias dr="python $rapl/azav/diffrot.py"
alias drr="python $rapl/azav/diffrot_rslice.py"
alias drder="python $rapl/azav/diffrot_derivs.py"
alias drdershav="python $rapl/azav/diffrot_derivs_shav.py"
alias amom="python $rapl/azav/amom.py"
alias mc="python $rapl/azav/mercirc.py"

# mean fields
alias Bmaz="python $rapl/azav/Bm_azav.py"

# torque
alias torque="python $rapl/azav/torque.py"
alias torquert="python $rapl/azav/torque_rt.py"

# thermal state
alias thermo="python $rapl/azav/thermo_merplane.py"
alias thermonond="python $rapl/azav/thermo_merplane_nond.py"
alias tw="python $rapl/azav/simple_thermal_wind.py"

# energy stuff
alias kem="python $rapl/azav/ke_merplane.py"
alias toten="python $rapl/azav/toten.py"
alias totenvst="python $rapl/azav/toten_vs_time.py"

# line plots
alias etr="python $rapl/timetrace/etrace.py"
alias axiB="python $rapl/how_axisym_B.py"
alias efr="python $rapl/shav/eflux_radial.py"
alias efrvst="python $rapl/shav/eflux_radial_vs_time.py"
alias vamp="python $rapl/shav/vamp.py"
alias bamp="python $rapl/shav/bamp.py"
alias vavamp="python $rapl/shav/va_to_vamp.py"
alias eft="python $rapl/eflux_latitudinal.py"
alias eft2="python $rapl/eflux_latitudinal-2.py"

# ortho
alias ortho="python $rapl/sslice/ortho_show.py"
alias orthorvals="python $rapl/sslice/ortho_rvals_sample.py"
alias orthovars="python $rapl/sslice/ortho_vars_sample.py"
alias orthotimes="python $rapl/sslice/ortho_times_sample.py"
alias orthomov="python $rapl/sslice/ortho_movie.py"

# moll
alias moll="python $rapl/sslice/moll_show.py"
alias mollrvals="python $rapl/sslice/moll_rvals_sample.py"
alias mollvars="python $rapl/sslice/moll_vars_sample.py"
alias mollmov="python $rapl/sslice/moll_movie.py"
alias mollazavtl="python $rapl/sslice/moll_azav_tl_movie.py"

# mer
alias mer="python $rapl/mer_show.py"
alias merlonvals="python $rapl/mer_lonvals_sample.py"
alias mervars="python $rapl/mer_vars_sample.py"
alias mertimes="python $rapl/mer_times_sample.py"
alias mermov="python $rapl/mer_movie.py"

# eq
alias eq="python $rapl/eq_show.py"
alias eqvars="python $rapl/eq_vars_sample.py"
alias eqtimes="python $rapl/eq_times_sample.py"
alias eqmov="python $rapl/eq_movie.py"

# speclm
alias speclm="python $rapl/spec_lm_show.py"
alias speclmrvals="python $rapl/spec_lm_rvals_sample.py"
alias speclmvars="python $rapl/spec_lm_vars_sample.py"
alias speclmtimes="python $rapl/spec_lm_times_sample.py"

alias specavlm="python $rapl/specav_lm_show.py"
alias specavlmrvals="python $rapl/specav_lm_rvals_sample.py"
alias specavlmvars="python $rapl/specav_lm_vars_sample.py"

# specl
alias specl="python $rapl/spec_l_show.py"
alias speclrvals="python $rapl/spec_l_rvals_sample.py"
alias speclvars="python $rapl/spec_l_vars_sample.py"
alias specltimes="python $rapl/spec_l_times_sample.py"

alias specavl="python $rapl/specav_l_show.py"
alias specavlrvals="python $rapl/specav_l_rvals_sample.py"
alias specavlvars="python $rapl/specav_l_vars_sample.py"

# time-(something), i.e., timey
alias timey="python $rapl/timetrace/timey.py"

# Remove spaces (not really a Rayleigh routine but need a spot for it)
alias rmspace="python $raco/remove_spaces.py"
