#!/bin/bash
# Author: Loren Matilsky
# Created: 07/07/2016
# Modified to work in new "environment" repo: 02/12/2021

# state what's going on
echo $bufferstring
echo "Executing $envdir/bashrc_mac"

# color code directory contents
alias ls="ls -G" # Works on Mac
#alias ls="ls --color='auto'" # Works on general Unix, but not Mac :-( FUCK YOU TIM COOK!!!

###############################
# Mac shortcuts               #
###############################
# Rayleigh simulation root directories on Mac (data previews)
export rasim=$HOME/rayleigh/sims
export tahy=$rasim/tachocline
export tady=$tahy/dynamo

# Main folders
export mu=$HOME/Music/Music/Media
export doc=$HOME/Documents
export down=$HOME/Downloads
export desk=$HOME/Desktop

# Desktop sub dirs
export pubrev=$desk/Publication_Review
export thesis=$desk/Thesis
export notes=$desk/Research_Notes
export pres=$desk/Presentations
export cv=$desk/CV

export papers=$desk/Paper_Library

export pub=$desk/Publications

export prop=$desk/Proposals
export proprsr=$doc/Proposal_to_Recruit_Support_Retain_UrMs_APS

export fin=$doc/Financial

# Switch hidden folder on and off
alias showhidden='defaults write com.apple.Finder AppleShowAllFiles true && killall Finder'
alias nohidden='defaults write com.apple.Finder AppleShowAllFiles false && killall Finder'

# Path variables
# Extra appendages for Mac
export PATH=$PATH:/opt/intel/bin
export PATH=$PATH:/Applications/VAPOR/VAPOR.app/Contents/MacOS

# Necessary to make Rayleigh dynamically link with MKL
export DYLD_LIBRARY_PATH=/opt/intel/compilers_and_libraries_2019.0.117/mac/mkl/lib
# Remove duplicate entries in PATH:
#case ":$PATH:" in
#	*":$new_entry:"*) :;; # already there
#	*) PATH="$new_entry:$PATH";; # or PATH="$PATH:$new_entry"
#esac

# Set the Intel MKL root directory
export MKLROOT=/opt/intel/mkl
export MKL_INCLUDE=$MKLROOT/include
export MKL_LIBRARY=$MKLROOT/lib

# Configure Rayleigh on Mac
export FC=mpif90
export CC=gcc
export FFTWROOT=/usr/local
export LAPACKROOT=/usr
export BLASROOT=/usr
alias configra='./configure --FC=$FC --CC=$CC --with-fftw=$FFTWROOT --with-lapack=$LAPACKROOT --with-blas=$BLASROOT'

# Aliases
alias osxversion='defaults read loginwindow SystemVersionStampAsString'
	# print running version of OSX
alias jn='jupyter notebook'

# Download an entire website (dangerous!)
alias website-dl='wget --mirror -nH -np -p -k -E -e robots=off'

# Use Stroustrup's stupid include file
#alias g++='g++ -std=c++11 -I/Users/loren/CPLUSPLUS'

# Make compiler tell about "All Warnings" ot learn 
# c++ as a beginner (-Wall option). 
#alias g++='g++ -Wall'

# Sync folders with papers between Mac and LCD
alias syncbooks='rsync -avP ~/Desktop/Books/ freyr:~/Desktop/Books && rsync -avP freyr:~/Desktop/Books/ ~/Desktop/Books'
alias syncproposals='rsync -avP ~/Desktop/Proposals/ freyr:~/Desktop/Proposals && rsync -avP freyr:~/Desktop/Proposals/ ~/Desktop/Proposals'
alias syncpresentations='rsync -avP ~/Desktop/Presentations/ freyr:~/Desktop/Presentations && rsync -avP freyr:~/Desktop/Presentations/ ~/Desktop/Presentations'

# source the common stuff
sbcommon
