#!/bin/bash
# Author: Loren Matilsky
# Created: 07/07/2016
# Updated: 05/05/2022

# state what's going on
echo $bufferstring
echo "Executing $envdir/bashrc_lcd"

# color code directory contents
alias ls="ls --color='auto'"

# some aliases 
alias lo='libreoffice'
alias jn='jupyter notebook'
alias sst='sup shiftc --status'

# stuff for remote (sup) shiftc transfers
shiftfrom () {
    sup shiftc --extract-tar lfe:~/$1/*.tar $2
}

shiftto () {
    sup shiftc --create-tar --index-tar $1 lfe:~/$2/name.tar
}

shist() {
    sup shiftc --history --id=$1
}

# Compiler environment variables
export INTEL_DISABLE_ISIP=1 # Stop ifort from creating annoying ~/intel/ism/rm empty directory
export OMP_NUM_THREADS=1
export FC=mpif90
export CC=mpicc

# Start the vnc server
# make vnc window to match the screen dimensions of freyr
# MUST deactivate from conda environment (both) first
alias vnc='de; de; vncserver -localhost -geometry 1900x1000' 
alias vncv='vncviewer'

# source the common stuff
sbcommon
