#!/bin/bash
# ~/rayleigh/utils shortcuts
# revised: 12/08/2022

# state what's going on
echo $bufferstring
echo "Executing $envdir/bashrc_ra_routines"

#####################################################
# compute routines
#####################################################

# print routines
alias findcorrupt="$ppc $raco/print_corrupt_files.py"
alias qi="python $raco/print_quantity_or_index.py"
alias ttrans="python $raco/print_translated_time.py"
alias simt="python $raco/print_simtime.py"
alias irate="python $raco/print_iter_rate.py"
alias nodestats="python $raco/print_nodestats.py"
alias readtime="python $raco/print_readtime.py"
alias sliceinfo="python $raco/print_sliceinfo.py"
alias qgroup="python $raco/print_qgroup.py"
alias printnumbersinput="python $raco/print_numbers_input.py"
alias printnumbersoutput="python $raco/print_numbers_output.py"
alias printlevels="python $raco/print_levels_other_aspects.py"
alias eqconst="python $raco/print_eq_constants.py"
alias freq="python $raco/print_output_freq.py"

# remove spaces (not really a Rayleigh routine but need a spot for it)
alias rmspace="python $raco/remove_spaces.py"

# data analysis routines (mostly parallelized)
alias tav="$ppc $raco/timeavg/radata.py"
alias gtr="$ppc $raco/timetrace/G_Avgs_quad.py"
alias ty="$ppc $raco/timetrace/timey.py"
alias mty="$ppc $raco/timetrace/mtrace_timey.py"
#alias mtytotmspec="$ppc $raco/timetrace/mtrace_to_tmspec.py"
alias mtytotmspec="python $raco/timetrace/mtrace_to_tmspec.py"
alias tavjoin="python $raco/timeavg/timeavg_join.py"
alias ttrjoin="python $raco/timetrace/timetrace_join.py"
alias gtrjoin="python $raco/timetrace/G_Avgs_quad_join.py"

# custom reference routines
alias refczrz="python $raco/reference_state/generate_CZRZ_reference.py"
alias heatczrz="python $raco/reference_state/generate_CZRZ_heating.py"
alias sigmakappa="python $raco/reference_state/lower_sigma_through_kappa.py"
alias heatcoolincz="python $raco/reference_state/generate_HeatingCooling_in_CZ.py"
alias computeouterdsdr="python $raco/reference_state/compute_outer_dsdr.py"
alias interpconst="python $raco/reference_state/interpret_constants.py"
alias diffrhopower="python $raco/reference_state/set_diffusions_rhopower.py"

#####################################################
# plot routines
#####################################################

# basic routines (main plot/ directory)
alias gridres="python $rapl/grid_resolution.py"
alias lengthscales="python $rapl/length_scales.py"
alias ref="python $rapl/reference.py"
alias eqfunc="python $rapl/eq_functions.py"
alias trans="python $rapl/transport.py"

# AZ_Avgs routines
alias azav="python $rapl/azav/azav.py"
alias dr="python $rapl/azav/diffrot.py"
alias drmcthermo="python $rapl/azav/diffrot_mercirc_thermo.py"
alias vplat="python $rapl/azav/vp_with_latprofiles.py"
alias pvhlat="python $rapl/azav/PVH_with_latprofiles.py"
alias pvslat="python $rapl/azav/PVS_with_latprofiles.py"
alias drr="python $rapl/azav/diffrot_rslice.py"
alias drder="python $rapl/azav/diffrot_derivs.py"
alias mc="python $rapl/azav/mercirc.py"
alias bpol="python $rapl/azav/bpol.py"
alias mcnd="python $rau/zz_legacy/mercirc_nondim_specificsuite.py"
alias thermoazav="python $rapl/azav/thermo.py"
alias thermalwind="python $rapl/azav/thermal_wind.py"
alias toten="python $rapl/azav/toten.py"
alias eft="python $rapl/azav/eflux_latitudinal.py"
alias tauv="python $rapl/azav/viscous_torque.py"

# Shell_Avgs routines
alias bamp="python $rapl/shav/bamp.py"
alias vamp="python $rapl/shav/vamp.py"
alias efr="python $rapl/shav/eflux_radial.py"
alias lfr="python $rapl/shav/Lflux_radial.py"
alias Lshell="python $rapl/shav/L_shell.py"
alias plotnumbersoutput="python $rapl/shav/numbers_output.py"
alias thermoshav="python $rapl/shav/thermo.py"

# timetrace routines
alias amomtr="python $rapl/timetrace/amomtrace_quad.py"
alias etr="python $rapl/timetrace/etrace_quad.py"
alias timetr="python $rapl/timetrace/timetrace_quad.py"
alias timey="python $rapl/timetrace/timey.py"
alias torsosc="python $rapl/timetrace/tors_osc.py"
alias mtimey="python $rapl/timetrace/mtrace_timey.py"

# slice plotting routines
alias raslice="$ppc $rapl/slice/raslice.py"
alias raslicend="$ppc $rau/zz_legacy/raslice_nondim_specificsuite.py"
alias spec="python $rapl/slice/spec.py"

# test manipulation routines
alias frep="python $ratx/freplace.py"
