#!/bin/bash

# .bashrc
# Author: Loren Matilsky
# Created: 07/07/2016

# don't break scp with echo in .bashrc
if [ -z "$PS1" ]; then
    return
fi

echo "=============================="
echo "Executing ~/.bashrc"
echo "ls -l ~/.bashrc"
echo `ls -l ~/.bashrc`
echo "=============================="

# color code directory contents
alias ls="ls --color='auto'"

PS1="\$(pwd) "

# Enable auto-completion in bash
source ~/git-bash-completion

# unload all module files, then load desired ones
module purge
#module load intel
#module load openmpi
module load ffmpeg

# Extra appendages to PATH to allow 
# programs to be installed locally
export PATH=$PATH:~/bin
export PATH=$PATH:~/usr/bin
export HOME_DEFAULT="$HOME"

# papers directories
export so="$HOME_DEFAULT/Desktop/00_Solar"
export st="$HOME_DEFAULT/Desktop/00_Stellar"
export fl="$HOME_DEFAULT/Desktop/00_Fluids"
export ast="$HOME_DEFAULT/Desktop/00_General_Astronomy"

# some aliases for freyr
alias vnc='de; vncserver -geometry 1278x719' # best geometry for Mac
alias vncv='vncviewer'
alias fn='find `pwd` -name ' # fn for "full name"
alias lo='libreoffice'
alias jn='jupyter notebook'
alias sst='sup shiftc --status'

shiftfrom () {
    sup shiftc --extract-tar lfe:~/$1/*.tar $2
}

shiftto () {
    sup shiftc --create-tar --index-tar $1 lfe:~/$2/name.tar
}

source ~/environment/bashrc_common
