#!/bin/bash
# Author: Loren Matilsky
# Created: 07/07/2016
# Updated: 05/05/2022

# state what's going on
echo $bufferstring
echo "Executing $envdir/bashrc_lcd"

# color code directory contents
alias ls="ls --color='auto'"

# Enable auto-completion in bash
source ~/git-bash-completion

# unload all module files, then load desired ones
module purge
#module load intel
#module load openmpi
#module load ffmpeg

# Main folders on LCD
export doc=$HOME/Documents
export down=$HOME/Downloads
export desk=$HOME/Desktop

# Desktop sub dirs
export pubrev=$desk/Publication_Review
export pres=$desk/Presentations
export papers=$desk/Paper_Library
export pub=$desk/Publications
export prop=$desk/Proposals
export fin=$desk/Financial

# some aliases 
alias lo='libreoffice'
alias jn='jupyter notebook'
alias sst='sup shiftc --status'

# stuff for remote (sup) shiftc transfers
shiftfrom () {
    sup shiftc --extract-tar lfe:~/$1/*.tar $2
}

shiftto () {
    sup shiftc --create-tar --index-tar $1 lfe:~/$2/name.tar
}

shist() {
    sup shiftc --history --id=$1
}

# Compiler environment variables
export INTEL_DISABLE_ISIP=1 # Stop ifort from creating annoying ~/intel/ism/rm empty directory
export OMP_NUM_THREADS=1
export FC=mpif90
export CC=mpicc

# source the common stuff
sbcommon
