#!/bin/bash
# state what's going on
echo $bufferstring
echo "Executing $brcconda"

# conda shortcuts, and get into pyt2_4 environment by default
module use -a /swbuild/analytix/tools/modulefiles
module load miniconda3/v4
alias pyt29='source activate pyt2_9'
alias de='conda deactivate'
pyt29
de # need to reload this to get the PATH right in a VNC
pyt29
