#!/bin/bash
# This set of commands gets called by all big environments
# Structure reintroduced: 05/06/2022
#
# state what's going on
echo $bufferstring
echo "Executing $envdir/bashrc_common"

# start by clearing all aliases
#unalias -a

# Make prompt show current working directory
# But only if bashrc_common hasn't been sourced already
if ! [ sourced_common_already ]; then
    PS1='\w$ '
fi

# Extra appendages to PATH to allow 
# programs to be installed locally
export PATH=$PATH:$HOME/bin
export PATH=$PATH:$HOME/usr/bin

#####################
#DIRECTORY STRUCTURES
#####################

# Python startup file
export PYTHONSTARTUP=$HOME/environment/python_startup.py
# Note: on Pleaides, there is also /etc/pythonstart, should I worry about this?

# Main folders
export doc=$HOME/Documents
export down=$HOME/Downloads
export desk=$HOME/HOMEtop

# universal HOMEtop subdirs (mostly on Mac)
export notes=$HOME/Research_Notes
export pubrev=$HOME/Publication_Review
export thesis=$HOME/Thesis
export pres=$HOME/Presentations
export cv=$HOME/CV
export papers=$HOME/Paper_Library
export pub=$HOME/Publications
export shared=$pub/Shared_Files
#export tachapj=$pub/Tacho_ApJ_Low_Sigma
#export tachnat=$pub/Tacho_Nat_Low_Sigma
export tachtorsosc=$pub/Tacho_ApJL_Torsosc
export sound1=$pub/Soundproof1_Anelastic
export sound2=$pub/Soundproof2_Boussinesq
export sound3=$pub/Soundproof2_Pseudoincompressible

export prop=$HOME/Proposals
export solartw=$HOME/Solar_Thermal_Wind

export proprsr=$HOME/Proposal_to_Recruit_Support_Retain_UrMs_APS
export fin=$HOME/Financial


# Rayleigh environent
export ra=$HOME/rayleigh
export racode=$ra/code
export rapp=$racode/post_processing

export raRyan=$HOME/rayleigh_Ryan
export racodeRyan=$raRyan/code
export rappRyan=$racodeRyan/post_processing

export rau=$ra/utils
export raco=$rau/compute # /usr/bin/co is a command
export rapl=$rau/plot # /usr/bin/plot is a command
export ratx=$rau/text 
export raleg=$rau/zz_legacy # /usr/bin/plot is a command
export idref=$raco/hydro_ideal_reference_state

# Pleiades directory shortcuts

# Rayleigh simulation root directories on Pleiades
export nb=/nobackup/lmatilsk
export nbnick=/nobackup/nfeather

# LCD  hard-disk shortcuts
export alt=/altair/loma3853
export pol=/pollux/loma3853
export cast=/castor/loma3853 #/usr/bin/cas is a program on Freyr
export sarg=/sargas/loma3853 # /usr/sbin/sargas is a program on Freyr
export miz=/mizar/loma3853

export postdoclcd=$alt/00_Summer_Postdoc-fresh

# LCD ssh shortcuts
export hyp=hyperion
export fre=freyr
export bac=bacchus
export tel=tellus
export hyd=hydra
export hyd2=hydra2
export scy=scylla

# Rayleigh simulation data
#
# Jupiter
export jupcz=$rasims/Jupiter_Wulff_CZonly
export jupwl=$rasims/Jupiter_Wulff_WL
export jupczroc2=$jupcz/CZonly_Roc0.20_Ra1.0e7
export jupwlroc2=$jupwl/WL_Roc0.20_Ra1.0e7
export jupcz2=$jupcz/CZonly_Roc0.20_Ra1.0e7-2
export jupczmhd=$jupcz/CZonly_Roc0.20_Ra1.0e7-mhd
export jupczhighra=$jupcz/CZonly_Roc0.20_Ra3.0e8
export jupwl2=$jupwl/WL_Roc0.20_Ra1.0e7-2
export jupcznoslip=$jupcz/CZonly_Roc0.20_Ra1.0e7-noslip
export jupwlnoslip=$jupwl/WL_Roc0.20_Ra1.0e7-noslip
export jupwlmhd=$jupcz/WL_Roc0.20_Ra1.0e7-mhd

export jupczroc14=$jupcz/CZonly_Roc0.14_Ra4.9e6
export jupwlroc14=$jupwl/WL_Roc0.14_Ra4.9e6

# Low-Sigma tachocline
export tachsims=$rasims/Tacho_ApJ_Low_Sigma_Sims
export m0=$tachsims/Loren_M_Bu5800
export m1=$tachsims/Lydia_M_Bu0.22_Ra5e6_Prm4
export m2=$tachsims/Lydia_M_Bu0.22_Ra1e6_Prm4
export m3=$tachsims/Loren_M_Bu0.17_Pr0.5_Prm4
export m4=$tachsims/Loren_M_Bu0.83_Pr0.1
export m5=$tachsims/Lydia_M_Bu2.2
export m6=$tachsims/Loren_M_Bu33

export h0=$tachsims/Loren_H_Bu5800
export h1=$tachsims/Lydia_H_Bu0.22_Ra5e6
export h2=$tachsims/Lydia_H_Bu0.22_Ra1e6
export h3=$tachsims/Loren_H_Bu0.17_Pr0.5
export h4=$tachsims/Loren_H_Bu0.83_Pr0.1
export h5=$tachsims/Lydia_H_Bu2.2
export h6=$tachsims/Loren_H_Bu33

export m1restart=$m1/00_restart
export m2restart=$m2/00_restart
export m5restart=$m5/00_restart

export h1restart=$h1/00_restart
export h2restart=$h2/00_restart
export h5restart=$h5/00_restart

export h1lyd=/nobackupp19/lkorre/solar_rot_conic/n2_A1_Ra5e6_Ek0.00045
export h2lyd=/nobackupp19/lkorre/solar_rot_conic/n2_A1_Ra1e6_Ek0.001
export h5lyd=/nobackupp19/lkorre/CZ-RZ_anelastic_ND/Rotating/Nrho=3/A10_d3e9_Ra1e6_Ek0.001

export m1lyd=/nobackupp19/lkorre/Magnetism/Pm4n2A1Ra5e6Ek0.00045
export m2lyd=/nobackupp19/lkorre/Magnetism/Pm4n2A1Ra1e6Ek0.001
export m5lyd=/nobackupp19/lkorre/Magnetism/Pm4n3A10Ra1e6Ek0.001
export m8lyd=/nobackupp19/lkorre/Magnetism/Pm4n2A1Ra5e6Ek0.00045
export m9lyd=/nobackupp19/lkorre/Magnetism/Pm4n3A10Ra1e6Ek0.001

# NSF sims
export nsfsims=$nb/NSF_Dynamo_SpinDown_Sims
export nsfsimshc=$nb/NSF_Dynamo_SpinDown_Sims/heatcool
export hroc10=$nsfsims/H_Roc0.100
export hroc15=$nsfsims/H_Roc0.150
export hroc20=$nsfsims/H_Roc0.200
export hroc25=$nsfsims/H_Roc0.250
export hroc30=$nsfsims/H_Roc0.300
export hroc35=$nsfsims/H_Roc0.350
export hroc40=$nsfsims/H_Roc0.400
export hroc45=$nsfsims/H_Roc0.450
export hroc52=$nsfsims/H_Roc0.516
export hroc59=$nsfsims/H_Roc0.590
export hroc67=$nsfsims/H_Roc0.667
export hroc73=$nsfsims/H_Roc0.730
export hroc80=$nsfsims/H_Roc0.800
export hroc90=$nsfsims/H_Roc0.900
export hroc100=$nsfsims/H_Roc1.000
export hroc200=$nsfsims/H_Roc2.000
export hroc500=$nsfsims/H_Roc5.000

export mroc10=$nsfsims/M_Roc0.100
export mroc15=$nsfsims/M_Roc0.150
export mroc20=$nsfsims/M_Roc0.200
export mroc25=$nsfsims/M_Roc0.250
export mroc30=$nsfsims/M_Roc0.300
export mroc35=$nsfsims/M_Roc0.350
export mroc40=$nsfsims/M_Roc0.400
export mroc45=$nsfsims/M_Roc0.450
export mroc52=$nsfsims/M_Roc0.516
export mroc59=$nsfsims/M_Roc0.590
export mroc67=$nsfsims/M_Roc0.667
export mroc73=$nsfsims/M_Roc0.730
export mroc80=$nsfsims/M_Roc0.800
export mroc90=$nsfsims/M_Roc0.900
export mroc100=$nsfsims/M_Roc1.000
export mroc200=$nsfsims/M_Roc2.000
export mroc500=$nsfsims/M_Roc5.000

# other command aliases
alias fn='find `pwd` -name ' # fn for "full name"
alias gt='gnome-terminal'
alias rmbigdata='rm -rf Checkpoints *_Slices Shell_Spectra'

# Get disk usage
get_du() {
    du -hsc * >> $(date +%F)_du
}

get_du_app() {
    du -hsc --apparent-size * >> $(date +%F)_du_app
}

# Source global definitions
if [ -f /etc/bashrc ]; then
    echo $bufferstring
    echo "Executing /etc/bashrc"
    . /etc/bashrc 
fi

# always ssh with display privileges
alias ssh='ssh -X'
alias less='less -MN' # make less show line numbers and  filename in status bar

# sym links
alias linkra='ln -s $racode/bin/rayleigh.opt'
alias linkdbg='ln -s $racode/bin/rayleigh.dbg'
alias linkmain='rm rayleigh.*; ln -s $racode/bin/main/rayleigh.* .'
alias linkmods='rm rayleigh.*; ln -s $racode/bin/allmods/rayleigh.* .'
alias linkcustom='rm rayleigh.*; ln -s $racode/bin/custom/rayleigh.* .'
alias linkperfcond='rm rayleigh.*; ln -s $racode/bin/perfcond/rayleigh.* .'
alias linkmulti='rm rayleigh.*; ln -s $racode/bin/multi/rayleigh.* .'
alias linkrome='rm rayleigh.*; ln -s /home4/nfeather/software/Rayleigh-Rome-2.28/bin/* .'

alias linknobinrz='rm rayleigh.*; ln -s $racode/bin/noBinRZ/rayleigh.* .'
alias linktraceback='rm rayleigh.*; ln -s $racode/bin/traceback/rayleigh.* .'

# post processing
alias runra='mpiexec -np 16 ./rayleigh.opt -nprow 4 -npcol 4'
alias runra1="./rayleigh.opt -nprow 1 -npcol 1"

# Configure rayleigh with .muck extension
alias configmuck='EXT=".muck" ./configure'

# Tar up some sample output (G_Avgs, Shell_Avgs, AZ_Avgs,
# Equatorial_Slices, Meridional_Slices, Shell_Slices, Shell_Spectra)
# as well as main_input, reference, transport, and grid_info for
# a given Rayleigh run directory

# Rayleigh routines

# parallel
# set default nproc based on hostname
host=`hostname`
if [[ "$host" == "lfe"* ]] || [[ "$host" == "pfe"* ]] || [[ "$host" == "LorensMac" ]] || [[ "$host" == "LorensOldMac" ]]; then
    nproc=1 # process in serial on the lfes, pfes and mac
    export ppc="python"
else
    nproc=`nproc --all` # by default, use max number of processes
    export ppc="mpiexec -n $nproc python -u"
fi
# ppc for "python parallel call"
#export ppc="mpiexec -n $nproc --oversubscribe python -u"
source $HOME/environment/bashrc_ra_routines

setnproc() {
    nproc=$1
    export ppc="mpiexec -n $nproc python -u"
    source $HOME/environment/bashrc_ra_routines
}

make_sample() {
    lastfile=`comm -12 <(ls -1 Shell_Slices/ | sort) <(ls -1 Meridional_Slices/ | sort) | tail -n 1`
    tar -cvf datasample.tar AZ_Avgs/$lastfile Equatorial_Slices/$lastfile G_Avgs/$lastfile Meridional_Slices/$lastfile  Shell_Avgs/$lastfile  Shell_Slices/$lastfile  Shell_Spectra/$lastfile main_input equation_coefficients grid_info jobinfo.txt
}
make_sampledata() {
    lastfile=`comm -12 <(ls -1 Shell_Slices/ | sort) <(ls -1 Meridional_Slices/ | sort) | tail -n 1`
    tar -cvf datasample.tar AZ_Avgs/$lastfile Equatorial_Slices/$lastfile G_Avgs/$lastfile Meridional_Slices/$lastfile  Shell_Avgs/$lastfile  Shell_Slices/$lastfile  Shell_Spectra/$lastfile main_input equation_coefficients grid_info jobinfo.txt data/
}
make_sampledataplots() {
    lastfile=`comm -12 <(ls -1 Shell_Slices/ | sort) <(ls -1 Meridional_Slices/ | sort) | tail -n 1`
    tar -cvf datasample.tar AZ_Avgs/$lastfile Equatorial_Slices/$lastfile G_Avgs/$lastfile Meridional_Slices/$lastfile  Shell_Avgs/$lastfile  Shell_Slices/$lastfile  Shell_Spectra/$lastfile main_input equation_coefficients grid_info jobinfo.txt data/ plots/
}

# count lines in a directory
# usage: countlines directory/ \*.[extension]
# NOTE: must include "\" before "*" so the wildcard doesn't get expanded
# when passed to the function ("\*" passes the asterisk verbatim in $2)
# Example:
# countlines compute/ \*py [note final slash is irrelevant; could use "compute"]
countlines() {
    find $1 -name "$2" -type f | xargs wc -l
}

countfiles() {
    find $1 -type f | wc -l
}

# sequentialize images in directory
alias sequence="python $raco/sequentialize_images.py"
# ffmpeg shortcut for making movies form img????.png files
#alias ffm="ffmpeg -framerate 30 -i img%04d.png -qscale 5 movie.mp4"
alias ffm="ffmpeg -framerate 30 -i img%04d.png -vf \"scale=ceil(iw/2)*2:ceil(ih/2)*2\" -c:v libx264 -pix_fmt yuv420p -preset medium -crf 23 -movflags +faststart movie.mp4"
# BASH SHORTCUTS
alias rmsslice="bash $rau/bash/rm_sslice.sh"
alias rmtexaux="rm *aux *bbl *blg *log *out *synctex.gz"

alias mvbashrc="mv ~/.bashrc ~/.bashrc-bak; mv ~/.bash_profile ~/.bash_profile-bak"
alias mvbashrcbak="mv ~/.bashrc-bak ~/.bashrc; mv ~/.bash_profile-bak ~/.bash_profile"

# say now we've sourced common
sourced_common_already=1
