#!/bin/bash
#
# the buffer string
export bufferstring="============================================================"

# state what's going on
echo $bufferstring
echo "Executing $HOME/environment/dotbash_profile"

# umask to make everything visible to others in my [group(s)?]
umask u=rwx,g=rx,o=

if [ -f $HOME/.bashrc ]; then
    source $HOME/.bashrc
fi
