#!/bin/bash

# .bashrc on LFE

# Note (04/20/22):
# This file sets the default environment on the PFEs / LFEs
# Very little of the environment is changed in this file per se
# loading all the "standard" settings is accomplished by running
# sbpfe (source the bashrc_pfe file in the ~/environment repo)
# ---or, analogously, sblfe
# this ensures the environments on compute nodes / pbspl1 remain 
# "uncorrupted" by default
# depending on the hostname, more defaults will be loaded via
# sbpfe, sblfe, sblcd, sbmac

# the following are environmental aliases
# in any environment, I have the option of getting into 
# my bigger environments)
export bufferstring="============================================================"

# specific HOME directory(s) (what $HOME defaults to on a given system)
export HOME_LFE=/lou/la2/lmatilsk
export HOME_PFE=/home1/lmatilsk
export HOME_LCD=/home5/loma3853
export HOME_MAC=/home/loren

# the environment git repo
export envdir=$HOME/environment

# short "dot bashrc" file (i.e., this file)
export dotbrc=$envdir/dotbashrc

# long bashrc files (the big environments)
export brcpfe=$envdir/bashrc_pfe
export brclfe=$envdir/bashrc_lfe
export brclcd=$envdir/bashrc_lcd
export brcmac=$envdir/bashrc_mac

# supporting "common" files for the big environments
export brccommon=$envdir/bashrc_common
export brcra=$envdir/bashrc_ra_routines

# commands to source each file
alias sbpfe="source $brcpfe"
alias sblfe="source $brclfe"
alias sbcommon="source $brccommon"
alias dotsbpfe="source $dotbrcpfe"
alias dotsblfe="source $dotbrclfe"

# commands to edit each file
alias vbpfe="vim $brcpfe"
alias vblfe="vim $brclfe"
alias vbcommon="vim $brccommon"
alias dotvbpfe="vim $dotbrcpfe"
alias dotvblfe="vim $dotbrclfe"


# Enable auto-completion in git
source /etc/bash_completion.d/git.sh # file is "git" (no suffix) on PFE

# only do anything (automatically) on LFE or LDAN
host=`hostname`
if [[ "$host" == "lfe"* ]] || [[ "$host" == "ldan"* ]]; then
    sblfe
fi
