#!/bin/bash

# .bashrc on LFE

# Note (04/20/22):
# This file sets the default environment on the PFEs
# Very little of the environment is changed in this file
# loading all the "standard" settings is accomplished by running
# sbpfe (source the bashrc_pfe file in the ~/environment repo)
# this ensures the environments on compute nodes / pbspl1 remain 
# "uncorrupted" by default

################################################
# THE FOLLOWING IS THE SAME FOR BOTH LFE AND PFE
# I want these here no matter what (basically, I want the option, 
# in any environment, of getting into my bigger environments)
################################################

export bufferstring="============================================================"

# Commands to source or edit my big, sloppy .bashrc
# (want these here no matter what)

# HOME directory(s)
export HOME_LFE=/lou/la2/lmatilsk
export HOME_PFE=/home1/lmatilsk

# long bashrc files
export brcpfe=$HOME/environment/bashrc_pfe
export brclfe=$HOME/environment/bashrc_lfe
export brccommon=$HOME/environment/bashrc_common

# shorter "dot bashrc" files
export dotbrcpfe=$HOME/environment/dotbashrc_pfe
export dotbrclfe=$HOME/environment/dotbashrc_lfe # i.e., this one!

# commands to source each file
alias sbpfe="source $brcpfe"
alias sblfe="source $brclfe"
alias sbcommon="source $brccommon"
alias dotsbpfe="source $dotbrcpfe"
alias dotsblfe="source $dotbrclfe"

# commands to edit each file
alias vbpfe="vim $brcpfe"
alias vblfe="vim $brclfe"
alias vbcommon="vim $brccommon"
alias dotvbpfe="vim $dotbrcpfe"
alias dotvblfe="vim $dotbrclfe"

# commands to load MPI and/or Firefox

# function to get into MPI environment 
# (for compiling/running Rayleigh)
loadmpi() {
    module purge 
    module load mpi-hpe
    module load comp-intel
}

# load firefox
alias loadff="module load firefox"

################################################
# THE FOLLOWING IS UNIQUE TO PFE
################################################

# Enable auto-completion in git
source /etc/bash_completion.d/git.sh # file is "git" (no suffix) on PFE

# only do anything (automatically) on LFE or LDAN
host=`hostname`
if [[ "$host" == "lfe"* ]] || [[ "$host" == "ldan"* ]]; then
    sblfe
fi
