#!/bin/bash

# .bashrc on PFE

export bufferstring="============================================================"

# Commands to source or edit my big, sloppy .bashrc and/or load MPI
# (want these here no matter what)
export brcpfe=/home1/lmatilsk/environment/bashrc_pfe
alias sbpfe="source $brcpfe"
alias vbpfe="vim $brcpfe"

# commands to edit this particular file
alias sbpfe="source $brcpfe"
alias vbpfe="vim $brcpfe"

# HOME directory(s)
export HOME_LFE=/lou/la2/lmatilsk
export HOME_PFE=/home1/lmatilsk
export HOME_DEFAULT=$HOME_PFE

#
# commands to edit this particular file
alias sblfe="source $brclfe"
alias vblfe="vim $brclfe"
# Commands to source or edit my big, sloppy .bashrc 
export brclfe=/home1/lmatilsk/environment/bashrc_lfe
alias sblfe="source $brclfe"
alias vblfe="vim $brclfe"
# Commands to source or edit my big, sloppy .bashrc and/or load MPI
# (want these here no matter what)
export brc=$HOME/.bashrc
alias sb="source $brc"
alias vb="vim $brc"



# Enable auto-completion in git
source /etc/bash_completion.d/git

# commands to load MPI and/or Firefox
# (want these here no matter what)

# function to get into MPI environment 
# (for compiling/running Rayleigh)
loadmpi() {
    module purge 
    module load mpi-hpe
    module load comp-intel
}

# only source bashrc_pfe automatically on LFE, PFE, or LDAN
export host=`hostname`
if [[ "$host" == "lfe"* ]] || [[ "$host" == "pfe"* ]] || [[ "$host" == "ldan"* ]]; then
    sbpfe
fi

# load firefox
alias loadff="module load firefox"
