#!/bin/bash
#
# the buffer string
export bufferstring="============================================================"

# state what's going on
echo $bufferstring
echo "Executing $HOME/environment/dotbash_profile"

if [ -f ~/.bashrc ]; then
    source $HOME/.bashrc
fi
