#!/bin/bash

# .bashrc on LFE

export bufferstring="============================================================"

# Enable auto-completion in git
source /etc/bash_completion.d/git.sh # (file is "git" (no suffix) on PFE)

# only do anything (automatically) on LFE, PFE, or LDAN
host=`hostname`
if [[ "$host" == "lfe"* ]] || [[ "$host" == "pfe"* ]] || [[ "$host" == "ldan"* ]]; then
    sblfe
fi

# function to get into MPI environment 
# (for compiling/running Rayleigh)
loadmpi() {
    module purge 
    module load mpi-hpe
    module load comp-intel
}
